title: Xuprints
description: >-
  Hi there! Here's where I keep notes for myself and others.
url: "https://kev-in-xu.github.io" # DO NOT include trailing slash

# Author Info
author:
  name: Kevin Xu
  email: kevinxu116@gmail.com
  avatar: "/assets/images/avatar.jpg"  # replace with your image if you'd like
  bio: "CS + Bio at Columbia"

# Theme Settings
minimal_mistakes_skin: default  # other options: dark, contrast, neon, etc.

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Navigation
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

# Navigation Links
header_pages:
  - _pages/about.md
  - _pages/projects.md
  - _pages/bookshelf.md
  - _pages/misc.md

# Footer Links
footer:
    links:
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/in/kevin-k-xu/"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/kev-in-xu"

# Plugins (only those supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Optional Analytics (leave blank if not using)
google_analytics: ""
