title: Xuprints
description: >-
  Hi there! Here's where I keep notes for myself and others.
url: "https://kev-in-xu.github.io" # DO NOT include trailing slash

# Author Info
author:
  name: Kevin Xu
  email: kevinxu116@gmail.com
  avatar: "/assets/images/avatar.jpg"  # replace with your image if you'd like
  bio: "CS + Bio at Columbia"

# Theme Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default  # other options: dark, contrast, neon, etc.

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Navigation
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

# Navigation Links
header_pages:
  - about.md
  - projects.md

# Plugins (only those supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional Analytics (leave blank if not using)
google_analytics: ""
